### ISSUE TITLE
How big is the master node snapshot?

### ISSUE THREAD

**Issue by elopio** [openrelayxyz/ethercattle-deployment#62]
Hello people!

This solution is super interesting for many experiments we want to do at Flashbots. I have questions, I hope this is the right place to do it. I'll send them as separate issues. The first one:

How big is the snapshot that you are taking on the master node?

**Comment by AusIV** [comment]
From the perspective of the database, master nodes are just Geth nodes. We have support for an S3 implementation of the ancients database (for historic block data), which can reduce the disk footprint, but in general master nodes are the same size as any other Geth node.

It's worth noting that master nodes must run with `--gcmode=archive`, which means they grow faster than regular nodes, but you can start with a fast sync / snapshot sync and then enable --gcmode=archive when you start using it as a master node.

Additionally, our Geth fork supports copying the current state trie into a new database, which prunes out historic data.
