### ISSUE TITLE
How long does it take to start a new replica?

### ISSUE THREAD

**Issue by elopio** [openrelayxyz/ethercattle-deployment#63]
How long does it take to start a new replica?

and related,

How often do you have to replace an unhealthy replica?

**Comment by AusIV** [comment]
We use some tricks to speed up replica start times.

We launch with AWS snapshots, which initially have slow performance. We use an overlay volume for writes coming from Kafka, which means the data being streamed from Kafka is not impacted by the slow snapshot performance, but requests will initially be impacted by snapshot performance. We do run `fio` to warm the snapshot volumes to get them up to full performance.

As far as how often we have to replace replicas: Typically we replace replicas as their overlay volumes fill up, which comes out to be every two weeks. It is possible to increase the size of the overlay volumes, and keep the replicas running indefinitely.
