### ISSUE TITLE
How bad is the performance Shared Key Value Store solution?

### ISSUE THREAD

**Issue by elopio** [openrelayxyz/ethercattle-deployment#64]
In the docs I read about the [Shared Key Value Store solution you tried](https://ether-cattle-initiative.readthedocs.io/en/latest/topics/design/index.html#shared-key-value-store)

I would like to know if you collected any measurement, or even any anecdotes you would like to share. That option is also very interesting for our experiments, and any experiences will help us to be better prepared.

Thank you! :)

**Comment by AusIV** [comment]
Those measurements were taken in early 2018, and I have not retained records over that time. My recollection is that blocks took at least 45 seconds to process, and that was at a time where block gas limits were substantially lower.
